parameters:

services:
    app.calendar_listener:
        class: AppBundle\Event\CalendarEventListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }